proxy_address_ipv4 = "192.168.70.104:1080"
forward_address_ipv4 = "142.250.69.46:80"
proxy_address_ipv6 = "[::1]:8080"
forward_address_ipv6 = "[::1]:80"

# [rules.test]
# action = "Forward"
# Ip = ["255.255.255.255", 8]
# port = [1, 2, 3]
# uid = [1, 2, 3]

# [rules.test7]
# action = "Forward"
# Ip = ["::1", 8]
# port = "1-1000"


# [rules.test1]
# action = "Allow"
# ipv4 = ["1.1.1.1", 24]


# [rules.test2]
# # action = "Forward"
# action = "Deny"
# ipv4 = ["1.1.1.1", 24]
# port = [80, 443, 22]


[rules.test3]
action = "Forward"
# ipv4 = ["1.1.1.1", 32]
path = "/usr/bin/"


# [rules.test4]
# action = "Proxy"
# ipv4 = ["1.1.1.1", 24]
# path = "/usr/bin/"
