proxy_address_ipv4 = "127.0.0.1:80"
forward_address_ipv4 = "142.250.69.142:80"
proxy_address_ipv6 = "[::1]:80"
forward_address_ipv6 = "[::1]:80"

[rules.test]
action = "Forward"
Ip = ["255.255.255.255", 8]
port = "1-10"
uid = "100"

[rules.test7]
action = "Forward"
Ip = ["::1", 8]
port = "1-1000"

[rules.test2]
action = "Forward"
# action = "Proxy"
Ip = ["1.1.1.1", 8]
port = "1-1000"

[rules.test3]
action = "Forward"
Ip = ["127.0.0.1", 8]
port = "1-1000"
