[package]
name = "ebpf-common"
version = "0.1.0"
edition = "2024"

[dependencies]
aya = { workspace = true, optional = true }
serde = { version = "1.0", default-features = false, features = ["derive"] }
heapless = "0.8.0"
postcard = "1.1.1"
[lib]
path = "src/lib.rs"

[features]
user = [ "aya" ]