[package]
name = "ebpf-common"
version = "0.1.0"
edition = "2024"

[dependencies]
aya = { workspace = true, default-features = false, optional = true }

[lib]
path = "src/lib.rs"

[features]
user = ["aya"]
